# Generated by Django 5.1.7 on 2025-03-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_leveling', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
