# Generated by Django 5.1.7 on 2025-03-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_leveling', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S'), ('Jinwoo', 'Jinwoo')], default='E', max_length=10),
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pushups', models.IntegerField(default=50)),
                ('situps', models.IntegerField(default=50)),
                ('squats', models.IntegerField(default=50)),
                ('running_km', models.FloatField(default=5.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
