# Generated by Django 5.1.7 on 2025-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_leveling', '0005_rename_streak_count_user_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
