# Generated by Django 5.1.7 on 2025-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_leveling', '0006_alter_dailytask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailytask',
            unique_together={('user', 'date')},
        ),
    ]
