# Generated by Django 5.1.7 on 2025-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_leveling', '0007_alter_dailytask_date_alter_dailytask_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eliminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
