# Generated by Django 5.1.7 on 2025-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_leveling', '0008_user_eliminated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='this_month_exp',
            field=models.IntegerField(default=0),
        ),
    ]
